---
world:
  gravity: 5000
keys:
  right: d
  left: a
  down: s
  up: w
sprites: resources/sprites/patato.png
levels:
  test level:
    patato:
    - 0
    - 0
entities:
  patato:
    animations:
      climbingIdle:
      - - - 17
          - 1
      - false
      climbingDown:
      - - - 16
          - 0.1
        - - 17
          - 0.1
        - - 18
          - 0.1
        - - 17
          - 0.1
      - true
      standing:
      - - - 1
          - 1
      - false
      walking:
      - - - 2
          - 0.1
        - - 3
          - 0.1
        - - 4
          - 0.1
        - - 3
          - 0.1
      - true
      crouchAttackingFlySwat:
      - - - 11
          - 0.03
        - - 12
          - 0.1
        - - 11
          - 0.05
      - false
      lyingDown:
      - - - 15
          - 1
      - false
      crouchWalking:
      - - - 6
          - 0.1
        - - 7
          - 0.1
        - - 8
          - 0.1
        - - 7
          - 0.1
      - true
      flyingHurt:
      - - - 14
          - 1
      - false
      climbingUp:
      - - - 18
          - 0.1
        - - 17
          - 0.1
        - - 16
          - 0.1
        - - 17
          - 0.1
      - true
      climbAttackingFlySwat:
      - - - 19
          - 0.03
        - - 20
          - 0.1
        - - 19
          - 0.05
      - false
      hit:
      - - - 13
          - 1
      - false
      climbingStartingJump:
      - - - 17
          - 0.04
      - false
      jumping:
      - - - 4
          - 1
      - false
      crouching:
      - - - 5
          - 1
      - false
      gettingUp:
      - - - 5
          - 0.1
      - false
      standAttackingFlySwat:
      - - - 9
          - 0.03
        - - 10
          - 0.1
        - - 9
          - 0.05
      - false
      startingJump:
      - - - 1
          - 0.04
      - false
    input:
      right: right
      left: left
    impulseSpeed:
      jump: 1200
      walk: 400
      climb: 400
      crouchWalk: 200
...
