name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "luajit-2.0.5"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: build
      run: luarocks install busted
      
    - name: test
      run: |
        busted ./engine